# Generated by Django 5.0.1 on 2024-02-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/profile.png', null=True, upload_to='media'),
        ),
    ]
