# Generated by Django 5.0.1 on 2024-03-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='principal_sign',
            field=models.ImageField(blank=True, default='sign.png', upload_to=''),
        ),
    ]
