# Generated by Django 5.0.1 on 2024-02-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_lostid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostid',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('cancelled', 'cancelled')], default='pending', max_length=200),
        ),
    ]
