# Generated by Django 5.0.1 on 2024-03-02 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_bathno'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('serial_number', models.PositiveIntegerField(unique=True)),
                ('id_number', models.PositiveIntegerField(unique=True)),
                ('back_serial', models.CharField(max_length=12)),
                ('random_number', models.CharField(max_length=200)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
            ],
        ),
    ]
