# Generated by Django 5.0.1 on 2024-03-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_idcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='back_serial',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='random_number',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
